spring.application.name=default
spring.cloud.txc.txcAppName=default
spring.cloud.txc.txcServerGroup=default


my.datasource.a.url=${DB1}
my.datasource.a.username=root
my.datasource.a.password=${DB1_PASSWORD}

my.datasource.b.url=${DB2}
my.datasource.b.username=root
my.datasource.b.password=${DB2_PASSWORD}

logging.level.com.taobao.spas=ERROR