spring:
  application:
    name: config-manager-aliyun-demo
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

io:
  cloudapp:
    config:
      aliyun:
        write:
          enabled: true
          timeout: 5000
          group: ${group:cloudapp}
          regionId: ${regionId:any}
          namespaceId: ${namespaceId}
          domain: ${dncs_endpoint}
          accessKey: ${AK}
          secretKey: ${SK}