spring:
  application:
    name: RocketMQ-Demo
#  config:
#    import: nacos:RocketMQ-Demo.yaml?refresh=true
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848

server:
  port: 8099

io:
  cloudapp:
    messaging:
      rocketmq:
        enabled: true
        nameServer: ${ROCKET_HOST}
        username: ${ROCKET_USERNAME}
        password: ${ROCKET_PASSWORD}
        useTLS: false
        enableMsgTrace: true
        #        traceTopic:
        inputs:
          - group: GID-test-group
            name: rocketConsumer
            topic: test-topic
            namespace: MQ_INST_1643347622121632_Blw6vZq0
        outputs:
          - name: rocketProducer
            #            messageModel: CLUSTERING
            group: GID-test-group
            namespace: MQ_INST_1643347622121632_Blw6vZq0
#            sendTimeout:
#            instanceName:
#            retryNextServer:
#            compressMsgBodyOverHowMuch:
#            maxMessageSize:
#            retryTimesWhenSendFailed:
